-- MySQL Script generated by MySQL Workbench
-- Tue Sep  2 19:24:15 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';
-- -----------------------------------------------------
-- Schema Inventario_axxion
-- -----------------------------------------------------
CREATE SCHEMA  Inventario_axxion DEFAULT CHARACTER SET utf8 ;
USE Inventario_axxion ;
drop database db_prueba;
-- ----------------------------------------------------

-- -----------------------------------------------------
-- Table categorias
-- -----------------------------------------------------
CREATE TABLE  categorias (
  id INT(10) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(200) NOT NULL,
  estado TINYINT(10) NOT NULL,
  descripción TIMESTAMP NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table Subcategorias
-- -----------------------------------------------------
CREATE TABLE Subcategorias (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(45) NOT NULL,
  categoria_id VARCHAR(45) NOT NULL,
  categorias_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_Subcategorias_categorias_id (categorias_id ASC),
  CONSTRAINT fk_Subcategorias_categorias
    FOREIGN KEY (categorias_id)
    REFERENCES categorias(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;


-- -----------------------------------------------------
-- Table alquiler
-- -----------------------------------------------------
CREATE TABLE  alquiler (
  id INT NOT NULL AUTO_INCREMENT,
  id_cliente VARCHAR(45) NOT NULL,
  fecha_salida VARCHAR(45) NOT NULL,
  id_producto VARCHAR(45) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table salida
-- -----------------------------------------------------
CREATE TABLE  salida (
  id INT NOT NULL,
  serial_producto VARCHAR(45) NOT NULL,
  fecha_de_creacion VARCHAR(45) NOT NULL,
  alquiler_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_salida_alquiler_id (alquiler_id ASC),
  CONSTRAINT fk_salida_alquiler
    FOREIGN KEY (alquiler_id)
    REFERENCES alquiler(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table proveedores
-- -----------------------------------------------------
CREATE TABLE  proveedores (
  id INT(10) NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(200) NOT NULL,
  telefono VARCHAR(200) NOT NULL,
  dirección TEXT NOT NULL,
  estado DATE NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table entradas
-- -----------------------------------------------------
CREATE TABLE  entradas (
  id INT NOT NULL AUTO_INCREMENT,
  id_provedor VARCHAR(45) NOT NULL,
  id_prodcuto VARCHAR(45) NOT NULL,
  proveedores_id INT(10) NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_entradas_proveedores_id (proveedores_id ASC),
  CONSTRAINT fk_entradas_proveedores
    FOREIGN KEY (proveedores_id)
    REFERENCES proveedores(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Productos
-- -----------------------------------------------------
CREATE TABLE  Productos (
  id INT NOT NULL AUTO_INCREMENT,
  nombre_productos VARCHAR(255) NOT NULL,
  detalle TEXT NOT NULL,
  estado TINYINT NOT NULL,
  stock_id INT NOT NULL,
  subcategorias_id INT NOT NULL,
  salida_id INT NOT NULL,
  entradas_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_productos_subcategorias_id (subcategorias_id ASC),
  INDEX fk_productos_salida_id (salida_id ASC),
  INDEX fk_productos_entradas_id (entradas_id ASC),
  CONSTRAINT fk_productos_subcategorias
    FOREIGN KEY (subcategorias_id)
    REFERENCES subcategorias(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_productos_salida
    FOREIGN KEY (salida_id)
    REFERENCES salida(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT fk_productos_entrada
    FOREIGN KEY (entradas_id)
    REFERENCES entradas(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table roles
-- -----------------------------------------------------
CREATE TABLE  roles (
  id INT(10) NOT NULL AUTO_INCREMENT,
  nombre_de_rol VARCHAR(200) NOT NULL,
  PRIMARY KEY (id))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table clientes
-- -----------------------------------------------------
CREATE TABLE  clientes (
  id INT(10) NOT NULL,
  stock_id INT NOT NULL,
  alquiler_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_clientes_alquiler_id (alquiler_id ASC),
  CONSTRAINT fk_clientes_alquiler
    FOREIGN KEY (alquiler_id)
    REFERENCES alquiler(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table Mantenimiento
-- -----------------------------------------------------
CREATE TABLE  Mantenimiento (
  id INT NOT NULL AUTO_INCREMENT,
  tipo_mantenimiento VARCHAR(45) NOT NULL,
  descripción TEXT NOT NULL,
  costo FLOAT NOT NULL,
  estado INT NOT NULL,
  Productos_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_Mantenimiento_Productos_id (Productos_id ASC),
  CONSTRAINT fk_Mantenimiento_Productos
    FOREIGN KEY (Productos_id)
    REFERENCES Productos(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table usuarios
-- -----------------------------------------------------
CREATE TABLE usuarios (
  id INT NOT NULL AUTO_INCREMENT,
  nombre VARCHAR(100) NOT NULL,
  correo_electronico VARCHAR(100) NOT NULL,
  contraseña VARCHAR(100) NOT NULL,
  recordar_token VARCHAR(100) NOT NULL,
  roles_id INT NOT NULL,
  direccion VARCHAR(45) NOT NULL,
  clientes_id INT NOT NULL,
  reporte_id INT NOT NULL,
  mantenimiento_id INT NOT NULL,
  mantenimiento_productos_id INT NOT NULL,
  PRIMARY KEY (id),
  INDEX fk_usuarios_roles_id (roles_id),
  INDEX fk_usuarios_clientes_id (clientes_id),
  INDEX fk_usuarios_mantenimiento_id (mantenimiento_id, mantenimiento_productos_id),
  CONSTRAINT fk_usuarios_roles
    FOREIGN KEY (roles_id)
    REFERENCES roles(id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION
) ENGINE=InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
